version: "3"
services:
  db:
    image: mysql:8.0.15
    container_name: mysql8015
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/docker/mysql:/var/lib/mysql